// flow-typed signature: 27a76bf883564bef61302a3efe156906
// flow-typed version: <<STUB>>/react-native-router-flux_v^4.0.0-beta.11/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-router-flux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-router-flux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-router-flux/__tests__/scenes.test' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/ActionConst' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/index' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/LightboxNavigator' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/NavBar' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/navigationStore' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/Reducer' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/Router' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/Scene' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/State' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/Util' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/ActionConst' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/index' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/LightboxNavigator' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/NavBar' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/navigationStore' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Reducer' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Router' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Scene' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Util' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/test/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-router-flux/__tests__/scenes.test.js' {
  declare module.exports: $Exports<'react-native-router-flux/__tests__/scenes.test'>;
}
declare module 'react-native-router-flux/dist/ActionConst.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/ActionConst'>;
}
declare module 'react-native-router-flux/dist/index.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/index'>;
}
declare module 'react-native-router-flux/dist/LightboxNavigator.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/LightboxNavigator'>;
}
declare module 'react-native-router-flux/dist/NavBar.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/NavBar'>;
}
declare module 'react-native-router-flux/dist/navigationStore.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/navigationStore'>;
}
declare module 'react-native-router-flux/dist/Reducer.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/Reducer'>;
}
declare module 'react-native-router-flux/dist/Router.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/Router'>;
}
declare module 'react-native-router-flux/dist/Scene.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/Scene'>;
}
declare module 'react-native-router-flux/dist/State.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/State'>;
}
declare module 'react-native-router-flux/dist/Util.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/Util'>;
}
declare module 'react-native-router-flux/src/ActionConst.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/ActionConst'>;
}
declare module 'react-native-router-flux/src/index.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/index'>;
}
declare module 'react-native-router-flux/src/LightboxNavigator.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/LightboxNavigator'>;
}
declare module 'react-native-router-flux/src/NavBar.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/NavBar'>;
}
declare module 'react-native-router-flux/src/navigationStore.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/navigationStore'>;
}
declare module 'react-native-router-flux/src/Reducer.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Reducer'>;
}
declare module 'react-native-router-flux/src/Router.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Router'>;
}
declare module 'react-native-router-flux/src/Scene.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Scene'>;
}
declare module 'react-native-router-flux/src/Util.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Util'>;
}
declare module 'react-native-router-flux/test/setup.js' {
  declare module.exports: $Exports<'react-native-router-flux/test/setup'>;
}
