// flow-typed signature: 8a8dd53d3e20ec66ddc2cd67440ddc2b
// flow-typed version: <<STUB>>/react-native-dotenv_v^0.1.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-dotenv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-dotenv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-dotenv/index' {
  declare module.exports: $Exports<'react-native-dotenv'>;
}
declare module 'react-native-dotenv/index.js' {
  declare module.exports: $Exports<'react-native-dotenv'>;
}
