// flow-typed signature: 6097ecf88f482c2dd3c52e483c289817
// flow-typed version: <<STUB>>/react-native-easy-grid_v^0.1.15/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-easy-grid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-easy-grid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-easy-grid/Components/_tests_/Col.test' {
  declare module.exports: any;
}

declare module 'react-native-easy-grid/Components/_tests_/Grid.test' {
  declare module.exports: any;
}

declare module 'react-native-easy-grid/Components/_tests_/Row.test' {
  declare module.exports: any;
}

declare module 'react-native-easy-grid/Components/Col' {
  declare module.exports: any;
}

declare module 'react-native-easy-grid/Components/Grid' {
  declare module.exports: any;
}

declare module 'react-native-easy-grid/Components/Row' {
  declare module.exports: any;
}

declare module 'react-native-easy-grid/Utils/computeProps' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-easy-grid/Components/_tests_/Col.test.js' {
  declare module.exports: $Exports<'react-native-easy-grid/Components/_tests_/Col.test'>;
}
declare module 'react-native-easy-grid/Components/_tests_/Grid.test.js' {
  declare module.exports: $Exports<'react-native-easy-grid/Components/_tests_/Grid.test'>;
}
declare module 'react-native-easy-grid/Components/_tests_/Row.test.js' {
  declare module.exports: $Exports<'react-native-easy-grid/Components/_tests_/Row.test'>;
}
declare module 'react-native-easy-grid/Components/Col.js' {
  declare module.exports: $Exports<'react-native-easy-grid/Components/Col'>;
}
declare module 'react-native-easy-grid/Components/Grid.js' {
  declare module.exports: $Exports<'react-native-easy-grid/Components/Grid'>;
}
declare module 'react-native-easy-grid/Components/Row.js' {
  declare module.exports: $Exports<'react-native-easy-grid/Components/Row'>;
}
declare module 'react-native-easy-grid/index' {
  declare module.exports: $Exports<'react-native-easy-grid'>;
}
declare module 'react-native-easy-grid/index.js' {
  declare module.exports: $Exports<'react-native-easy-grid'>;
}
declare module 'react-native-easy-grid/Utils/computeProps.js' {
  declare module.exports: $Exports<'react-native-easy-grid/Utils/computeProps'>;
}
